;;; tools-project-detect.el --- Project Type Detection & Lang Pre-warming -*- lexical-binding: t -*-
;;; Version: 3.0.4
;;; Code:

(require 'cl-lib)
(require 'core-dev)

(defvar emacs-ide-modules-dir
  (expand-file-name "modules" user-emacs-directory)
  "Directory containing feature modules.")

(defvar emacs-ide-detect--lang-module-overrides
  '(("javascript" . "lang-web")
    ("typescript" . "lang-web")
    ("haskell"    . "lang-functional")
    ("clojure"    . "lang-functional")
    ("elixir"     . "lang-functional")
    ("erlang"     . "lang-functional")
    ("ocaml"      . "lang-functional")
    ("java"       . "lang-jvm")
    ("kotlin"     . "lang-jvm")
    ("scala"      . "lang-jvm")
    ("groovy"     . "lang-jvm")
    ("zig"        . "lang-systems")
    ("nix"        . "lang-systems")
    ("d"          . "lang-systems")
    ("v"          . "lang-systems")
    ("r"          . "lang-data")
    ("julia"      . "lang-data")
    ("yaml"       . "lang-prose")
    ("dockerfile" . "lang-prose")
    ("terraform"  . "lang-prose")
    ("ansible"    . "lang-prose"))
  "Alist of (LANG-KEY . MODULE-NAME) for langs with non-standard module names.")

(defvar emacs-ide-detect--markers
  '(("pyproject.toml"      . ("python"     "lang-python"     nil))
    ("setup.py"            . ("python"     "lang-python"     nil))
    ("setup.cfg"           . ("python"     "lang-python"     nil))
    ("requirements.txt"    . ("python"     "lang-python"     nil))
    ("Pipfile"             . ("python"     "lang-python"     nil))
    ("poetry.lock"         . ("python"     "lang-python"     nil))
    ("Cargo.toml"          . ("rust"       "lang-rust"       nil))
    ("go.mod"              . ("go"         "lang-go"         nil))
    ("go.sum"              . ("go"         "lang-go"         nil))
    ("package.json"        . ("javascript" "lang-web"        nil))
    ("tsconfig.json"       . ("typescript" "lang-web"        nil))
    ("next.config.js"      . ("typescript" "lang-web"        nil))
    ("vite.config.ts"      . ("typescript" "lang-web"        nil))
    ("CMakeLists.txt"      . ("c"          "lang-c"          nil))
    ("Makefile"            . ("c"          "lang-c"          nil))
    ("meson.build"         . ("c"          "lang-c"          nil))
    ("pom.xml"             . ("java"       "lang-jvm"        nil))
    ("build.gradle"        . ("java"       "lang-jvm"        nil))
    ("build.gradle.kts"    . ("kotlin"     "lang-jvm"        nil))
    ("settings.gradle"     . ("java"       "lang-jvm"        nil))
    (".luarc.json"         . ("lua"        "lang-lua"        nil))
    ("rockspec"            . ("lua"        "lang-lua"        nil))
    ("project.clj"         . ("clojure"    "lang-functional" nil))
    ("deps.edn"            . ("clojure"    "lang-functional" nil))
    ("shadow-cljs.edn"     . ("clojure"    "lang-functional" nil))
    ("stack.yaml"          . ("haskell"    "lang-functional" nil))
    ("package.yaml"        . ("haskell"    "lang-functional" nil))
    ("cabal.project"       . ("haskell"    "lang-functional" nil))
    ("build.sbt"           . ("scala"      "lang-jvm"        nil))
    ("build.sc"            . ("scala"      "lang-jvm"        nil))
    ("flake.nix"           . ("nix"        "lang-systems"    nil))
    ("default.nix"         . ("nix"        "lang-systems"    nil))
    ("build.zig"           . ("zig"        "lang-systems"    nil))
    ("build.zig.zon"       . ("zig"        "lang-systems"    nil))
    ("docker-compose.yml"  . ("yaml"       "lang-prose"      nil))
    ("Dockerfile"          . ("dockerfile" "lang-prose"      nil))
    (".terraform"          . ("terraform"  "lang-prose"      nil))
    ("terraform.tf"        . ("terraform"  "lang-prose"      nil))
    ("ansible.cfg"         . ("ansible"    "lang-prose"      nil)))
  "Alist of (MARKER-FILE . (LANG-KEY MODULE-NAME WARMUP-FN-OR-NIL)).")

(defvar emacs-ide-detect--ext-map
  '(("py"    . "python")
    ("pyw"   . "python")
    ("rs"    . "rust")
    ("go"    . "go")
    ("js"    . "javascript")
    ("mjs"   . "javascript")
    ("cjs"   . "javascript")
    ("ts"    . "typescript")
    ("tsx"   . "typescript")
    ("jsx"   . "javascript")
    ("c"     . "c")
    ("h"     . "c")
    ("cpp"   . "c")
    ("cc"    . "c")
    ("cxx"   . "c")
    ("hpp"   . "c")
    ("java"  . "java")
    ("kt"    . "kotlin")
    ("kts"   . "kotlin")
    ("scala" . "scala")
    ("sc"    . "scala")
    ("lua"   . "lua")
    ("sh"    . "shell")
    ("bash"  . "shell")
    ("zsh"   . "shell")
    ("fish"  . "shell")
    ("sql"   . "sql")
    ("r"     . "r")
    ("R"     . "r")
    ("jl"    . "julia")
    ("hs"    . "haskell")
    ("lhs"   . "haskell")
    ("clj"   . "clojure")
    ("cljs"  . "clojure")
    ("cljc"  . "clojure")
    ("zig"   . "zig")
    ("nix"   . "nix")
    ("rb"    . "ruby")
    ("ex"    . "elixir")
    ("exs"   . "elixir")
    ("php"   . "php")
    ("md"    . "prose")
    ("org"   . "prose")
    ("yml"   . "prose")
    ("yaml"  . "prose")
    ("toml"  . "prose")
    ("json"  . "prose"))
  "Alist of (EXTENSION . LANG-KEY) for fallback extension-based detection.")

(defvar emacs-ide-detect--pre-warmed nil
  "Hash table of already pre-warmed lang keys.")

(defun emacs-ide-detect--init-cache ()
  (unless (hash-table-p emacs-ide-detect--pre-warmed)
    (setq emacs-ide-detect--pre-warmed (make-hash-table :test 'equal))))

(defun emacs-ide-detect--project-root ()
  (cond
   ((and (fboundp 'projectile-project-root)
         (ignore-errors (projectile-project-root)))
    (ignore-errors (projectile-project-root)))
   ((and (fboundp 'project-root)
         (project-current))
    (project-root (project-current)))
   (t nil)))

(defun emacs-ide-detect--scan-root (root)
  (when (and root (file-directory-p root))
    (let (found)
      (dolist (entry emacs-ide-detect--markers)
        (let* ((marker      (car entry))
               (info        (cdr entry))
               (marker-path (expand-file-name marker root)))
          (when (file-exists-p marker-path)
            (push (car info) found))))
      (delete-dups found))))

(defun emacs-ide-detect--module-for-lang (lang-key)
  (let ((entry (cl-find lang-key emacs-ide-detect--markers
                        :key (lambda (e) (car (cdr e)))
                        :test #'string=)))
    (when entry (cadr (cdr entry)))))

(defun emacs-ide-detect--prewarm-lang (lang-key)
  (emacs-ide-detect--init-cache)
  (when (and (emacs-ide-dev-lang-enabled-p lang-key)
             (not (gethash lang-key emacs-ide-detect--pre-warmed)))
    (puthash lang-key t emacs-ide-detect--pre-warmed)
    (let* ((module-name (or (cdr (assoc lang-key
                                        emacs-ide-detect--lang-module-overrides))
                            (emacs-ide-detect--module-for-lang lang-key)
                            (concat "lang-" lang-key)))
           (module-file (expand-file-name
                         (concat "langs/" module-name ".el")
                         emacs-ide-modules-dir)))
      (when (file-exists-p module-file)
        (run-with-idle-timer
         0.5 nil
         (lambda ()
           (condition-case err
               (progn
                 (load module-file nil t t)
                 (message "project-detect: pre-warmed %s" lang-key))
             (error
              (message "project-detect: failed to pre-warm %s: %s"
                       lang-key err)))))))))

(defun emacs-ide-detect-on-project-switch ()
  (let* ((root  (emacs-ide-detect--project-root))
         (langs (emacs-ide-detect--scan-root root)))
    (when langs
      (message "project-detect: detected langs %s in %s"
               (mapconcat #'identity langs ", ")
               (abbreviate-file-name (or root "")))
      (dolist (lang langs)
        (emacs-ide-detect--prewarm-lang lang)))))

(defun emacs-ide-detect-on-find-file ()
  (when buffer-file-name
    (let* ((root    (emacs-ide-detect--project-root))
           (markers (emacs-ide-detect--scan-root root))
           (ext     (file-name-extension buffer-file-name))
           (lang    (cdr (assoc (downcase (or ext ""))
                                emacs-ide-detect--ext-map))))
      (when (and lang (null markers))
        (emacs-ide-detect--prewarm-lang lang)))))

(add-hook 'projectile-after-switch-project-hook
          #'emacs-ide-detect-on-project-switch)

(add-hook 'find-file-hook #'emacs-ide-detect-on-find-file)

(defun emacs-ide-detect-current-project ()
  (interactive)
  (let* ((root  (emacs-ide-detect--project-root))
         (langs (emacs-ide-detect--scan-root root)))
    (if langs
        (message "Detected: %s in %s"
                 (mapconcat #'identity langs ", ")
                 (abbreviate-file-name (or root "no root")))
      (message "No project markers found — extension fallback active"))))

(defun emacs-ide-detect-reset-cache ()
  (interactive)
  (setq emacs-ide-detect--pre-warmed nil)
  (message "project-detect: cache cleared"))

(defun emacs-ide-detect-show-status ()
  (interactive)
  (with-output-to-temp-buffer "*Project Detect Status*"
    (princ "=== PROJECT DETECT STATUS (v3.0.4) ===\n\n")
    (princ (format "Project root:  %s\n"
                   (or (emacs-ide-detect--project-root) "none")))
    (let ((langs (emacs-ide-detect--scan-root (emacs-ide-detect--project-root))))
      (princ (format "Detected langs: %s\n\n"
                     (if langs (mapconcat #'identity langs ", ") "none"))))
    (princ "Pre-warmed:\n")
    (when (hash-table-p emacs-ide-detect--pre-warmed)
      (if (> (hash-table-count emacs-ide-detect--pre-warmed) 0)
          (maphash (lambda (k _)
                     (princ (format "  ✓ %s\n" k)))
                   emacs-ide-detect--pre-warmed)
        (princ "  (none yet)\n")))
    (unless (hash-table-p emacs-ide-detect--pre-warmed)
      (princ "  (cache not initialised yet)\n"))
    (princ "\nRegistered lang modules:\n")
    (if (fboundp 'emacs-ide-dev-registered-langs)
        (dolist (lang (emacs-ide-dev-registered-langs))
          (let ((enabled (emacs-ide-dev-lang-enabled-p lang)))
            (princ (format "  %s %s\n" (if enabled "✓" "✗") lang))))
      (princ "  (core-dev not loaded)\n"))))

(provide 'tools-project-detect)
;;; tools-project-detect.el ends here
